version: 2
updates:
  # Python packages
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
    reviewers:
      - Animatea
    rebase-strategy: auto
    target-branch: main
