version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.10-browsers-legacy
    working_directory: ~/src
    steps:
      - checkout
      - run:
          # Installing dev-requirements.txt.
          name: install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r dev-requirements.txt
      - run:
          # Running tests with installed dependencies.
          name: run tests
          command: |
            . venv/bin/activate
            pytest
            behave
      # Saving test results.
      - run:
          name: Creating Dummy Artifacts
          command: |
              echo "my artifact file" > /tmp/art-1;
              mkdir /tmp/artifacts;
              echo "my artifact files in a dir" > /tmp/artifacts/art-2;
      - store_artifacts:
          path: /tmp/art-1
          destination: artifact-file

      - store_artifacts:
          path: /tmp/artifacts
