site_name: "Aiotense docs"
site_url: https://tense.com/
repo_url: https://github.com/Animatea/tense
repo_name: Animatea/tense
edit_uri: https://github.com/Animatea/tense/tree/main/docs/docs

nav:
    - Home: index.md
    - "FAQ":
        - "Ukraine": uk_faq.md
        - "English": en_faq.md
        - "Russian": ru_faq.md

theme:
    name: material
    language: en
    favicon: tense-logo-filled-circle.png
    palette:
      - scheme: default
        primary: deep orange
        accent: teal
        toggle:
          icon: material/weather-sunny
          name: Switch to dark mode
      - scheme: slate
        primary:  deep orange
        accent: teal
        toggle:
          icon: material/weather-night
          name: Switch to light mode
    font:
      text: Ubuntu
    features:
      - navigation.instant
      - navigation.tracking
      - navigation.sections
      - navigation.expand
      - navigation.top

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

copyright: >
  Copyright &copy; 2022 Animatea –
  <a href="https://github.com/Animatea/aiotense/blob/main/LICENSE">License</a>

plugins:
  - search:
      lang:
        - ru
        - en
